use_frameworks!

target 'SBExpandableLabel_Example' do
  pod 'SBExpandableLabel', :path => '../'

  target 'SBExpandableLabel_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
